%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/solgaleo/Documents/Columbia Courseworks/Algorithmic Trading/Project/data/crypto.csv
%
% Auto-generated by MATLAB on 22-Apr-2020 21:46:49

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Hour", "BTC", "ETH", "XRP", "BCH", "USDT", "LTC", "EOS"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
crypto = readtable("/Users/solgaleo/Documents/Columbia Courseworks/Algorithmic Trading/Project/data/crypto.csv", opts);


%% Clear temporary variables
clear opts